"""add_is_primary_to_photos

Revision ID: 113e6d20706c
Revises: 0cb28629b161
Create Date: 2025-03-15 21:48:03.915979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '113e6d20706c'
down_revision = '0cb28629b161'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # まず、NULLを許可するカラムを追加
    op.add_column('photos', sa.Column('is_primary', sa.Boolean(), nullable=True))
    
    # 既存のレコードにデフォルト値を設定
    op.execute(text("UPDATE photos SET is_primary = FALSE"))
    
    # カラムをNOT NULLに変更
    op.alter_column('photos', 'is_primary', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'is_primary')
    # ### end Alembic commands ###
