"""Add Google Places API fields to Spot model

Revision ID: 13dcb60c2176
Revises: 
Create Date: 2025-03-01 18:27:52.979973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13dcb60c2176'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('google_place_id', sa.String(length=255), nullable=True))
    op.add_column('spots', sa.Column('formatted_address', sa.String(length=255), nullable=True))
    op.add_column('spots', sa.Column('types', sa.Text(), nullable=True))
    op.add_column('spots', sa.Column('thumbnail_url', sa.String(length=255), nullable=True))
    # SQLiteではALTER COLUMNがサポートされていないため、型変更の部分を削除
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLiteではALTER COLUMNがサポートされていないため、型変更の部分を削除
    op.drop_column('spots', 'thumbnail_url')
    op.drop_column('spots', 'types')
    op.drop_column('spots', 'formatted_address')
    op.drop_column('spots', 'google_place_id')
    # ### end Alembic commands ###
