"""update_photo_model_for_postgresql

Revision ID: 15846cf6d16e
Revises: 2288abc9f4fd
Create Date: 2025-03-04 19:28:30.369426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '15846cf6d16e'
down_revision = '2288abc9f4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'is_google_photo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('photos', 'is_google_photo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
