"""Add job fields to import_progress

Revision ID: 17b3783dc5b5
Revises: 0001_baseline
Create Date: 2025-07-01 00:32:49.694465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b3783dc5b5'
down_revision = '0001_baseline'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_progress', sa.Column('job_id', sa.String(length=36), nullable=True))
    op.add_column('import_progress', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('import_progress', sa.Column('result_data', sa.Text(), nullable=True))
    op.add_column('import_progress', sa.Column('error_info', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'import_progress', ['job_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'import_progress', type_='unique')
    op.drop_column('import_progress', 'error_info')
    op.drop_column('import_progress', 'result_data')
    op.drop_column('import_progress', 'status')
    op.drop_column('import_progress', 'job_id')
    # ### end Alembic commands ###
