"""Remove google_photo_reference columns

Revision ID: 4f4568c19a1a
Revises: 6176834b995d
Create Date: 2025-06-14 20:27:55.216346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f4568c19a1a'
down_revision = '6176834b995d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'google_photo_reference')
    op.drop_column('spots', 'google_photo_reference')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('google_photo_reference', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('google_photo_reference', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
