"""Add rating and review_count to Spot model

Revision ID: 53a2478728c8
Revises: 2ed08e78ed1a
Create Date: 2025-06-14 17:00:57.159576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a2478728c8'
down_revision = '2ed08e78ed1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('rating', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('spots', sa.Column('review_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'review_count')
    op.drop_column('spots', 'rating')
    # ### end Alembic commands ###
