"""Add rating and review_count to Spot model

Revision ID: 6176834b995d
Revises: 53a2478728c8
Create Date: 2025-06-14 20:05:36.165219

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6176834b995d'
down_revision = '53a2478728c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=False, server_default='0.0'))
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spots', schema=None) as batch_op:
        batch_op.drop_column('review_count')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
