"""Add import history tracking fields

Revision ID: 66dcced61b55
Revises: 113e6d20706c
Create Date: 2025-03-15 22:55:23.077316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66dcced61b55'
down_revision = '113e6d20706c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_history', sa.Column('last_post_id', sa.String(length=255), nullable=True))
    op.add_column('import_history', sa.Column('last_post_timestamp', sa.DateTime(), nullable=True))
    op.add_column('import_history', sa.Column('next_page_cursor', sa.String(length=255), nullable=True))
    op.add_column('import_history', sa.Column('total_imported_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_history', 'total_imported_count')
    op.drop_column('import_history', 'next_page_cursor')
    op.drop_column('import_history', 'last_post_timestamp')
    op.drop_column('import_history', 'last_post_id')
    # ### end Alembic commands ###
