"""Add Google photo reference fields to Photo model

Revision ID: 761e85bfa4d5
Revises: 13dcb60c2176
Create Date: 2025-03-02 13:29:57.752894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '761e85bfa4d5'
down_revision = '13dcb60c2176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns
    op.add_column('photos', sa.Column('google_photo_reference', sa.String(length=255), nullable=True))
    op.add_column('photos', sa.Column('is_google_photo', sa.Boolean(), nullable=True))
    
    # SQLite doesn't support ALTER COLUMN directly, so we'll use a workaround
    # for the photo_url column by setting a default value for existing rows
    conn = op.get_bind()
    conn.execute('UPDATE photos SET photo_url = photo_url')
    
    # Type changes for latitude and longitude
    op.alter_column('spots', 'latitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('spots', 'longitude',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('spots', 'longitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('spots', 'latitude',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    
    # For downgrade, we need to ensure all photo_url values are not NULL
    conn = op.get_bind()
    conn.execute('UPDATE photos SET photo_url = "" WHERE photo_url IS NULL')
    
    op.drop_column('photos', 'is_google_photo')
    op.drop_column('photos', 'google_photo_reference')
    # ### end Alembic commands ###
