"""Add google_photo_reference to Spot model

Revision ID: a0930fab9652
Revises: 761e85bfa4d5
Create Date: 2025-03-02 14:13:11.409369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
import logging

# revision identifiers, used by Alembic.
revision = 'a0930fab9652'
down_revision = '761e85bfa4d5'
branch_labels = None
depends_on = None

logger = logging.getLogger('alembic.migration')

def column_exists(table, column):
    """指定されたカラムがテーブルに存在するかチェック"""
    bind = op.get_bind()
    conn = bind.connect()
    try:
        # PostgreSQLのinformation_schemaからカラムの存在を確認
        result = conn.execute(
            text(
                "SELECT EXISTS (SELECT 1 FROM information_schema.columns "
                "WHERE table_name = :table AND column_name = :column)"
            ),
            {"table": table, "column": column}
        ).scalar()
        return result
    finally:
        conn.close()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # カラムが存在しない場合のみ追加
    if not column_exists('spots', 'google_photo_reference'):
        op.add_column('spots', sa.Column('google_photo_reference', sa.String(length=255), nullable=True))
        logger.info("Added google_photo_reference column to spots table")
    else:
        logger.info("google_photo_reference column already exists in spots table, skipping")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists('spots', 'google_photo_reference'):
        op.drop_column('spots', 'google_photo_reference')
        logger.info("Dropped google_photo_reference column from spots table")
    else:
        logger.info("google_photo_reference column does not exist in spots table, skipping")
    # ### end Alembic commands ###
