"""add summary location to spots

Revision ID: add_summary_location_to_spots
Revises: eac5a8692401
Create Date: 2024-03-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_summary_location_to_spots'
down_revision = 'eac5a8692401'  # 現在のヘッドを指定
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('summary_location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'summary_location')
    # ### end Alembic commands ### 