"""Add autoreply fields to User model

Revision ID: create_autoreply_fields
Revises: 4fa78cecc172
Create Date: 2025-03-30 15:24:37.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'create_autoreply_fields'
down_revision = '4fa78cecc172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('autoreply_enabled', sa.Boolean(), nullable=True, default=False))
    op.add_column('users', sa.Column('autoreply_template', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('autoreply_last_updated', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('instagram_business_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'website')
    op.drop_column('users', 'instagram_business_id')
    op.drop_column('users', 'autoreply_last_updated')
    op.drop_column('users', 'autoreply_template')
    op.drop_column('users', 'autoreply_enabled')
    # ### end Alembic commands ### 