"""Update import_history for pagination

Revision ID: dcbc8c45c3de
Revises: 66dcced61b55
Create Date: 2025-03-15 23:07:14.697221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dcbc8c45c3de'
down_revision = '66dcced61b55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_history', 'last_post_timestamp')
    op.drop_column('import_history', 'next_page_cursor')
    op.drop_column('import_history', 'total_imported_count')
    op.drop_column('import_history', 'last_post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_history', sa.Column('last_post_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('import_history', sa.Column('total_imported_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('import_history', sa.Column('next_page_cursor', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('import_history', sa.Column('last_post_timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
