"""Add spots_heading to User model

Revision ID: eac5a8692401
Revises: 08c1e21c669b
Create Date: 2025-03-02 22:09:24.340695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
import logging

# revision identifiers, used by Alembic.
revision = 'eac5a8692401'
down_revision = '08c1e21c669b'
branch_labels = None
depends_on = None

logger = logging.getLogger('alembic.migration')

def column_exists(table, column):
    """指定されたカラムがテーブルに存在するかチェック"""
    bind = op.get_bind()
    conn = bind.connect()
    try:
        # PostgreSQLのinformation_schemaからカラムの存在を確認
        result = conn.execute(
            text(
                "SELECT EXISTS (SELECT 1 FROM information_schema.columns "
                "WHERE table_name = :table AND column_name = :column)"
            ),
            {"table": table, "column": column}
        ).scalar()
        return result
    finally:
        conn.close()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not column_exists('users', 'spots_heading'):
        op.add_column('users', sa.Column('spots_heading', sa.String(length=50), nullable=True))
        logger.info("Added spots_heading column to users table")
    else:
        logger.info("spots_heading column already exists in users table, skipping")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists('users', 'spots_heading'):
        op.drop_column('users', 'spots_heading')
        logger.info("Dropped spots_heading column from users table")
    else:
        logger.info("spots_heading column doesn't exist in users table, skipping")
    # ### end Alembic commands ###
