"""Add spots_heading to User model

Revision ID: eac5a8692401
Revises: 08c1e21c669b
Create Date: 2025-03-02 22:09:24.340695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eac5a8692401'
down_revision = '08c1e21c669b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('spots_heading', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'spots_heading')
    # ### end Alembic commands ###
