"""add wallet tables and event_log

Revision ID: ed7a33d3f885
Revises: 876b8da44193
Create Date: 2025-08-30 20:41:24.098416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed7a33d3f885'
down_revision = '876b8da44193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_spot_provider_ids_spot_provider', table_name='spot_provider_ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_spot_provider_ids_spot_provider', 'spot_provider_ids', ['spot_id', 'provider'], unique=True)
    # ### end Alembic commands ###
