"""Add import period columns to ImportProgress

Revision ID: 09d8b7b730ac
Revises: d5c138f83f42
Create Date: 2025-03-18 11:40:43.635382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d8b7b730ac'
down_revision = 'd5c138f83f42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_progress', sa.Column('import_period_start', sa.DateTime(), nullable=True))
    op.add_column('import_progress', sa.Column('import_period_end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_progress', 'import_period_end')
    op.drop_column('import_progress', 'import_period_start')
    # ### end Alembic commands ###
