"""Add password reset fields

Revision ID: 0cb28629b161
Revises: 4fa78cecc172
Create Date: 2025-03-14 16:36:25.159790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb28629b161'
down_revision = '4fa78cecc172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expires_at')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
