"""add_is_primary_to_photos

Revision ID: 113e6d20706c
Revises: 0cb28629b161
Create Date: 2025-03-15 21:48:03.915979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
import sqlalchemy.exc


# revision identifiers, used by Alembic.
revision = '113e6d20706c'
down_revision = '0cb28629b161'
branch_labels = None
depends_on = None


def column_exists(table, column):
    """指定されたカラムがテーブルに存在するかチェック"""
    bind = op.get_bind()
    conn = bind.connect()
    try:
        # PostgreSQLのinformation_schemaからカラムの存在を確認
        result = conn.execute(
            text(
                "SELECT EXISTS (SELECT 1 FROM information_schema.columns "
                "WHERE table_name = :table AND column_name = :column)"
            ),
            {"table": table, "column": column}
        ).scalar()
        return result
    finally:
        conn.close()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 'is_primary'カラムが存在するかチェック
    if not column_exists('photos', 'is_primary'):
        # カラムが存在しない場合のみ追加
        # まず、NULLを許可するカラムを追加
        op.add_column('photos', sa.Column('is_primary', sa.Boolean(), nullable=True))
        
        # 既存のレコードにデフォルト値を設定
        op.execute(text("UPDATE photos SET is_primary = FALSE"))
        
        # カラムをNOT NULLに変更
        op.alter_column('photos', 'is_primary', nullable=False)
    else:
        print("is_primary カラムはすでに存在します。スキップします。")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists('photos', 'is_primary'):
        op.drop_column('photos', 'is_primary')
    else:
        print("is_primary カラムが存在しないため、スキップします。")
    # ### end Alembic commands ###
