"""add facebook integration fields

Revision ID: add_facebook_integration_fields
Revises: fix_missing_columns
Create Date: 2025-03-19 14:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_facebook_integration_fields'
down_revision = 'fix_missing_columns'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('facebook_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('facebook_page_id', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('facebook_connected_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('webhook_subscription_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'webhook_subscription_id')
    op.drop_column('users', 'facebook_connected_at')
    op.drop_column('users', 'facebook_page_id')
    op.drop_column('users', 'facebook_token')
    # ### end Alembic commands ### 