"""add summary location to spots

Revision ID: add_summary_location_to_spots
Revises: eac5a8692401
Create Date: 2024-03-21 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text
import logging

# revision identifiers, used by Alembic.
revision = 'add_summary_location_to_spots'
down_revision = 'eac5a8692401'
branch_labels = None
depends_on = None

logger = logging.getLogger('alembic.migration')

def column_exists(table, column):
    """指定されたカラムがテーブルに存在するかチェック"""
    bind = op.get_bind()
    conn = bind.connect()
    try:
        # PostgreSQLのinformation_schemaからカラムの存在を確認
        result = conn.execute(
            text(
                "SELECT EXISTS (SELECT 1 FROM information_schema.columns "
                "WHERE table_name = :table AND column_name = :column)"
            ),
            {"table": table, "column": column}
        ).scalar()
        return result
    finally:
        conn.close()

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # カラムが存在しない場合のみ追加
    if not column_exists('spots', 'summary_location'):
        op.add_column('spots', sa.Column('summary_location', sa.String(length=255), nullable=True))
        logger.info("Added summary_location column to spots table")
    else:
        logger.info("summary_location column already exists in spots table, skipping")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if column_exists('spots', 'summary_location'):
        op.drop_column('spots', 'summary_location')
        logger.info("Dropped summary_location column from spots table")
    else:
        logger.info("summary_location column does not exist in spots table, skipping")
    # ### end Alembic commands ### 